### ISSUE TITLE
What does the cf argument mean?

### ISSUE THREAD

**Issue by Jiaxin-Wen** [zzzace2000/robust_cls_model#2]
https://github.com/zzzace2000/robust_cls_model/blob/c2b9a79dd5ccbb8aa8beaa08baaded6ed45d0410/train_pl.py#L56
https://github.com/zzzace2000/robust_cls_model/blob/9f5268933952f988630323daf5e0fabe9621c1d8/arch/lightning/base.py#L406
I've noticed that the cf value would change the calculation of the counterfactual loss, but I don't really understand that.

**Comment by zzzace2000** [comment]
Hi,

Please see the the last paragraph of the page 2 in the paper for details. The idea is 'logp' is the option (1), 'uni' is the option 2, and ''uni_e" is the option 3. 

![image](https://user-images.githubusercontent.com/6828559/140620812-bb292594-9d6f-4763-b421-1626e98167db.png)
 
"channels" is an idea that we test but it did not work so we did not write it in our paper. Basically we had an idea that we add an additional class that represents "no such class object exists in the image", and we optimize the cf loss on those classes. It performs quite poorly.

**Comment by Jiaxin-Wen** [comment]
thanks!
